config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :restaurants do
    # prefixed by /restaurants

    resources :reviews, only: [:new, :create]

   # get restaurants/:restaurant_id/reviews/new
   # post restaurants/:restaurant_id/reviews

    collection do
      get "/top", to: "restaurants#top" # prefixes /restaurants
    end

    member do
      get "/chef", to: "restaurants#chef" # prefixes /restaurants/:id
    end

  end

  resources :reviews, only: :destroy # DELETE reviews/:id

# New

# Create



# Destroy












 #  restaurants GET    /restaurants(.:format)                                                                            restaurants#index
 #                 POST   /restaurants(.:format)                                                                            restaurants#create
 #  new_restaurant GET    /restaurants/new(.:format)                                                                        restaurants#new
 # edit_restaurant GET    /restaurants/:id/edit(.:format)                                                                   restaurants#edit
 #      restaurant GET    /restaurants/:id(.:format)                                                                        restaurants#show
 #                 PATCH  /restaurants/:id(.:format)                                                                        restaurants#update
 #                 PUT    /restaurants/:id(.:format)                                                                        restaurants#update
 #                 DELETE /restaurants/:id(.:format)                                                                        restaurants#destroy


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true, length: { minimum: 4}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :chef]

  # GET /restaurants
  def index
    @restaurants = Restaurant.all
  end

  def top
    @restaurants = Restaurant.where(stars: 5).limit(5) # ActiveRecord Collection

    # @restaurants.where(name: "Sikha").joins()
    # Restaurant.all.select { |restaurant| restaurant.stars == 5 }.first(5)
  end

  def chef
    # restaurants/:id/chef
    @chef_name = @restaurant.chef_name

  end

  # GET /restaurants/1
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /restaurants/1
  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /restaurants/1
  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :stars)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)

    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantReviews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :stars %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/chef.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 mx-auto">
      <h1><%= @restaurant.name %></h1>

      <h2>Chef:</h2>
      <h3><%= @chef_name %></h3>

      <br>

      <h4>Bio:</h4>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda iusto sapiente vel at quam. Ex nihil reiciendis aliquid reprehenderit quia officia deleniti, accusantium aut mollitia libero blanditiis officiis laborum soluta!</p>

    </div>
  </div>
</div>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Stars</th>
      <th>Chef</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.stars %></td>
        <td><%= link_to restaurant.chef_name, chef_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 mx-auto">
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Name:</strong>
        <%= @restaurant.name %>
      </p>

      <p>
        <strong>Address:</strong>
        <%= @restaurant.address %>
      </p>

      <p>
        <strong>Stars:</strong>
        <%= @restaurant.stars %>
      </p>

    <ul>
      <% @restaurant.reviews.each do |review| %>
        <li><%= review.content %> - <%= link_to "x", review_path(review), method: "delete",
         class: "text-danger", data: { confirm: "Are you sure?"} %></li>
      <% end %>
    </ul>

    <%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
    <%= link_to 'Back', restaurants_path %>
    <%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>

    </div>
  </div>
</div>

app/views/restaurants/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 mx-auto">
      <h1>These are the top restos</h1>

      <ul>
        <% @restaurants.each do |restaurant| %>
          <li> <%= restaurant.name %> - <%= restaurant.stars %> </li>
        <% end %>
      </ul>

    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<h1>Leave a review for <%= @restaurant.name %>:</h1>


<!-- post /restaurants/44/reviews -->
<%= simple_form_for [@restaurant ,@review] do |f| %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>